version: '3.8'

services:
  result-reporter:
    build: .
    image: ghcr.io/ls1intum/hades-reporter/hades-reporter:latest
    container_name: hades-reporter
    environment:
      - ENDPOINT=https://hades-benchmarker.wei-tech.site/v1/start_time
    restart: "no"
